CREATE TABLE USERS (
    USERNAME NVARCHAR2(128) PRIMARY KEY,
    PASSWORD NVARCHAR2(500) NOT NULL,
    ENABLED CHAR(1) CHECK (ENABLED IN ('Y','N'))
);

CREATE TABLE AUTHORITIES (
    USERNAME NVARCHAR2(128) NOT NULL,
    AUTHORITY NVARCHAR2(128) NOT NULL,

    CONSTRAINT AUTHORITIES_PK
     PRIMARY KEY(USERNAME, AUTHORITY),

    CONSTRAINT AUTHORITIES_FK
     FOREIGN KEY(USERNAME)
         REFERENCES USERS(USERNAME)
);

-- Password = 12345

INSERT INTO USERS VALUES(
    'admin',
    '$2a$12$M5BtUfC1FltmsQxKGGEYsOTPValBBXWIgo6GC2Df0rvbPXRblAXZu',
    'Y'
);

INSERT INTO USERS VALUES(
    'jakir',
    '$2a$12$M5BtUfC1FltmsQxKGGEYsOTPValBBXWIgo6GC2Df0rvbPXRblAXZu',
    'Y'
);

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('admin', 'ROLE_ADMIN');

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('jakir', 'ROLE_USER');

COMMIT;

-- Check
SELECT * FROM AUTHORITIES;
SELECT * FROM USERS;
SELECT * FROM USERS FETCH NEXT 100 ROWS ONLY;

SELECT USERNAME, PASSWORD, ENABLED
FROM USERS;

SELECT USERNAME, AUTHORITY
FROM AUTHORITIES;